/* modifier 0 means no modifier */
static Key keys[] = {
    /* modifier	            keyval      function        arg             Focus */
    { 0,                    GDK_Escape, hidesearch,     {0},            ALWAYS },
    { 0,                    GDK_Escape, hideurl,        {0},            ALWAYS },
    { GDK_CONTROL_MASK,     GDK_P,      print,          {0},            ALWAYS },
    { 0,                    GDK_Return, searchtext,     {.b = TRUE},    SEARCHBAR },
    { GDK_SHIFT_MASK,       GDK_Return, searchtext,     {.b = FALSE},   SEARCHBAR },
    { GDK_CONTROL_MASK,     GDK_n,      searchtext,     {.b = TRUE},    BROWSER|SEARCHBAR },
    { GDK_CONTROL_MASK,     GDK_N,      searchtext,     {.b = FALSE},   BROWSER|SEARCHBAR },
    { 0 },
    { GDK_CONTROL_MASK,     GDK_R,      reload,         {.b = TRUE},    ALWAYS },
    { GDK_CONTROL_MASK,     GDK_r,      reload,         {.b = FALSE},   ALWAYS },
    { GDK_CONTROL_MASK,     GDK_g,      showurl,        {0},            ALWAYS },
    { GDK_CONTROL_MASK,     GDK_slash,  showsearch,     {0},            ALWAYS },
    { 0,                    GDK_Return, loaduri,        {.v = NULL},    URLBAR },
    { 0,                    GDK_Return, hideurl,        {0},            URLBAR },
    { GDK_CONTROL_MASK,     GDK_p,      clipboard,      {.b = TRUE },   BROWSER },
    { GDK_CONTROL_MASK,     GDK_y,      clipboard,      {.b = FALSE},   BROWSER },
    { GDK_CONTROL_MASK,     GDK_plus,   zoompage,       {.i = +1 },     BROWSER },
    { GDK_CONTROL_MASK,     GDK_minus,  zoompage,       {.i = -1 },     BROWSER },
    { GDK_CONTROL_MASK,     GDK_0,      zoompage,       {.i = 0 },      BROWSER },
    { GDK_CONTROL_MASK,     GDK_l,      navigate,       {.i = +1},      BROWSER },
    { GDK_CONTROL_MASK,     GDK_h,      navigate,       {.i = -1},      BROWSER },
    { 0,                    GDK_Escape, stop,           {0},            BROWSER },
};
