.TH SURF 1 surf\-VERSION
.SH NAME
surf \- simple webkit-based browser
.SH SYNOPSIS
.B surf
.RB [-e\ xid]
.RB [-i]
.RB [-p]
.RB [-s]
.RB [-v]
.RB [-x]
.RB "URI"
.SH DESCRIPTION
surf is a simple Web browser based on WebKit/GTK+. It is able
to display websites and follow links. It supports the XEmbed protocol
which makes it possible to embed it in another application. Furthermore,
one can point surf to another URI by setting its XProperties.
.SH OPTIONS
.TP
.B \-e xid
Reparents to window specified by xid.
.TP
.B \-i
Disable Images
.TP
.B \-p
Disable Plugins
.TP
.B \-s
Disable Javascript
.TP
.B \-v
Prints version information to standard output, then exits.
.TP
.B \-x
Prints xid to standard output. This can be used to script the browser by using
.BR xprop(1).
.SH USAGE
.B Escape
Stops loading current page or stops download.
.TP
.B Ctrl\-h
Walks back the history.
.TP
.B Ctrl\-l
Walks forward the history.
.TP
.B Ctrl\-k
Scrolls page upwards.
.TP
.B Ctrl\-j
Scrolls page downwards.
.TP
.B Ctrl\-Shift\-k
Zooms page in.
.TP
.B Ctrl\-Shift\-j
Zooms page out
.TP
.B Ctrl\-Shift\-i
Resets Zoom
.TP
.B Ctrl\-/
Opens the search-bar.
.TP
.B Ctrl\-n
Go to next search result.
.TP
.B Ctrl\-Shift\-n
Go to previous search result.
.TP
.B Ctrl\-g
Opens the URL-bar.
.TP
.B Ctrl\-p
Loads URI from primary selection.
.TP
.B Ctrl\-Shift\-p
Calls Printpage Dialog.
.TP
.B Ctrl\-r
Reloads the website.
.TP
.B Ctrl\-Shift\-r
Reloads the website without using cache.
.TP
.B Ctrl\-y
Copies current URI to primary selection.
.TP
.B Ctrl\-o
show the sourcecode of the current page.
.SH SEE ALSO
.BR dmenu(1)
.BR xprop(1)
.SH BUGS
Please report them!
